import "./globals.css";
import { Footer } from '@/components/shares/nav'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='flex flex-col min-h-screen'>
        <main className='relative overflow-hidden bg_dashboard flex-1'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
